{
    parserClass="me.dmitvitalii.apdp.lang.BlueprintParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Blueprint"
    psiImplClassSuffix="Impl"
    psiPackage="me.dmitvitalii.apdp.lang.psi"
    psiImplPackage="me.dmitvitalii.apdp.lang.psi.impl"

    elementTypeHolderClass="me.dmitvitalii.apdp.lang.psi.BlueprintType"
    elementTypeClass="me.dmitvitalii.apdp.lang.psi.BlueprintElementType"
    tokenTypeClass="me.dmitvitalii.apdp.lang.psi.SimpleTokenType"
}

simpleFile ::= item_*
private item_ ::= (property|COMMENT|CRLF)
property ::= (KEY? SEPARATOR VALUE?) | KEY
